config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  resources :home
  resources :roles
  resources :profiles

  # post "/profiles" => "profiles#create"
  # match 'users/sign_out' => "devise/sessions#destroy"
  root "home#index"
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :roles
  belongs_to :users

  has_attached_file :avatar, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
    "#{self.first} #{self.last}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first
    devise_parameter_sanitizer.for(:sign_up) << :last
    devise_parameter_sanitizer.for(:sign_up) << :gender
    devise_parameter_sanitizer.for(:sign_up) << :birth
    devise_parameter_sanitizer.for(:sign_up) << :user
    devise_parameter_sanitizer.for(:sign_up) << :avatar

    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :first
    devise_parameter_sanitizer.for(:account_update) << :last
    devise_parameter_sanitizer.for(:account_update) << :gender
    devise_parameter_sanitizer.for(:account_update) << :birth
    devise_parameter_sanitizer.for(:account_update) << :user
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  protected

  def get_current_user
    @user = current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def show
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < BaseController
  before_action :find_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @users = User.all.order("created_at DESC")
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    generated_password = Devise.friendly_token.first(8)
    @user.password = generated_password
    # @user.user = current_user
    if @user.save
      redirect_to profile_path, notice: "Usuario Creado"
    else
      flash[:error] = "Hubo un error al crear este usuario #{@user.errors.full_messages}"
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_profile
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first,:last,:email,:gender,:birth)
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  private

  def set_params
    @role = Role.find(params[:id])
  end

  def roles_params
    params.require(:role).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/home/index.html.erb
<h1>Bienvenidos</h1>

app/views/home/show.html.erb
<h1>Show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UsersAcl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="" class="navbar-brand">Profiles App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Nuevo Perfil",new_profile_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email,edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else  %>
            <li><%= link_to "Login",new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@user, url: registration_path(@user)) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first, label: "Nombre", required: true %>
      <%= f.input :last, label: "Apellido",required: true %>

      <%= f.input :email, required: true, autofocus: true %>
      <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
      <%= f.input :password_confirmation, required: true %>

      <%= f.input :gender, label: "Género", required: true %>
      <%= f.input :birth, label:"Fecha Nacimiento",required: true %>

    </div>

    <div class="form-actions">
      <%= f.button :submit, "Crear" %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<h2>Edit <%=@user.email %> account</h2>

<%= render "form" %>

app/views/profiles/index.html.erb
<div class="content">
  <div class="row">
    <h2>Lista de usuarios</h2>
    <table>
        <% @users.each do |user|  %>
        <tr>
          <td>
            <%= user.full_name %>
          </td>
          <td>
            <%= user.email %>
          </td>
          <td>
            <%= user.gender %>
          </td>
          <td>
            <%= link_to "Editar",edit_profile_path(user), class: "data" %>
          </td>
          <td>
            <%= link_to "Borrar",profiles_path(user), method: :delete, data: {confirm: "Esta seguro ?"}, class: "data" %>
          </td>
        </tr>
        <% end %>

    </table>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= simple_form_for(User.new, url: "/profiles") do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first, label: "Nombre", required: true %>
      <%= f.input :last, label: "Apellido",required: true %>

      <%= f.input :email, required: true, autofocus: true %>

      <%= f.input :gender, label: "Género", required: true %>
      <%= f.input :birth, label:"Fecha Nacimiento",required: true %>

    </div>

    <div class="form-actions">
      <%= f.button :submit, "Crear" %>
    </div>
<% end %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/roles/index.html.erb
<h1>Roles#index</h1>
<p>Find me in app/views/roles/index.html.erb</p>

app/views/roles/show.html.erb
<h1>Roles#show</h1>
<p>Find me in app/views/roles/show.html.erb</p>